FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12 as build

WORKDIR /usr/src
COPY package*.json ./
RUN npm install

#dev-cmd-live=npm run livepush

COPY src ./src
COPY tsconfig.json .
RUN npm run build

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:12

WORKDIR /usr/src

COPY package*.json ./
COPY --from=build /usr/src/build ./build

RUN npm install --production

CMD [ "npm", "start" ]