FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12

WORKDIR /usr/src

COPY package*.json ./
RUN npm install

#dev-cmd-live=npm run livepush

COPY ./src src
COPY tsconfig.json .
RUN npm run build

CMD [ "node", "/usr/src/build/index.js" ]