#!/bin/bash
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

name=$(sed 's/\"//g' <<< $NAME)
if [[ ! $name =~ ^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$ ]]; then exit 0; fi

action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")

case "$action" in
add)
    printf "discoverable off\npairable off\nexit\n" | bluetoothctl
    mplayer -volume 75 /usr/src/sounds/connect.mp3 -really-quiet > /dev/null 2>&1
    amixer sset PCM,0 100% > /dev/null &
    ;;
remove)
    mplayer -volume 75 /usr/src/sounds/disconnect.mp3 -really-quiet > /dev/null 2>&1
    printf "discoverable on\npairable on\nexit\n" | bluetoothctl
    amixer sset PCM,0 100% > /dev/null &
    ;;
esac
