#!/bin/bash
# set the discoverable timeout here
dbus-send --system --dest=org.bluez --print-reply /org/bluez/hci0 org.freedesktop.DBus.Properties.Set string:'org.bluez.Adapter1' string:'DiscoverableTimeout' variant:uint32:0

echo -e "\nSetting volume to 100%\n"
amixer sset PCM,0 100% > /dev/null &

service bluetooth restart
sleep 2
echo -e 'discoverable on\npairable on\nexit\n' | bluetoothctl

/usr/src/bluetooth-agent &

sleep 2
rm -rf /var/run/bluealsa/
/usr/bin/bluealsa -i hci0 -p a2dp-sink &

hciconfig hci0 up
hciconfig hci0 name "balenaSound-$(hostname)"

sleep 2
/usr/bin/bluealsa-aplay --pcm-buffer-time=1000000 00:00:00:00:00:00
