FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:edge

WORKDIR /usr/src

RUN install_packages snapcast-server
COPY snapserver.conf /etc/snapserver.conf
COPY start.sh .

CMD [ "/bin/bash", "/usr/src/start.sh" ]