FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

RUN install_packages gmediarender gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-alsa

COPY start.sh /usr/src/
RUN chmod +x /usr/src/start.sh

COPY .asoundrc /root/.asoundrc

CMD [ "/bin/bash", "/usr/src/start.sh" ]
