FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.12

ARG SNAPCAST_VERSION
RUN install_packages snapcast-server

WORKDIR /usr/src
COPY snapserver.conf /etc/snapserver.conf
COPY start.sh /usr/src/
RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]