FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.12

ARG SNAPCAST_VERSION
RUN install_packages snapcast-client

WORKDIR /usr/src
COPY start.sh /usr/src/
RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
