FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.11

ARG SNAPCAST_VERSION
RUN install_packages snapcast-client=$SNAPCAST_VERSION --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

WORKDIR /usr/src
COPY start.sh /usr/src/
RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
