FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu:latest
ENV ROON_DATAROOT /var/RoonBridge
ENV ROON_ID_DIR /var/RoonBridge
RUN install_packages curl ffmpeg
WORKDIR /opt/RoonBridge
ADD roonbridge-installer-linuxarmv8.sh /opt/RoonBridge
RUN chmod +x roonbridge-installer-linuxarmv8.sh && ./roonbridge-installer-linuxarmv8.sh
VOLUME [ "/opt/RoonBridge" ]
ENTRYPOINT /opt/RoonBridge/start.sh
