FROM balenalib/raspberrypi4-64-ubuntu:latest
COPY roonbridge-installer-linuxarmv8.sh /usr/src/roon-bridge
RUN cd /usr/src/roon-bridge/roonbridge-installer-linuxarmv8.sh && chmod +x roonbridge-installer-linuxarmv8.sh && ./roonbridge-installer-linuxarmv8.sh
