FROM balenalib/raspberrypi4-64-ubuntu:latest
COPY roonbridge-installer-linuxarmv8.sh /usr/src/roon-bridge
RUN chmod +x /usr/src/roon-bridge/roonbridge-installer-linuxarmv8.sh
CMD [ "/bin/bash", "/usr/src/roonbridge-installer-linuxarmv8.sh" ]
