#!/usr/bin/python
# This sript runs, when your pi connects to a bluetooth device and BLUETOOTH_CONNECT is set to anything.
# You can add your own code. BalenaSound has gpiozero installed so you can work with it.
# Here is a example:

# from gpiozero import LED
# from time import sleep

# led = LED(17)

# led.off()
# sleep(1)

